import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import localFont from "next/font/local";

const GeogrotesqueWide = localFont({
  src: "../public/fonts/GeogrotesqueWide-Rg.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeogrotesqueWide.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
